-- DROP TABLE IF EXISTS `beerTypeDescription`;
-- DROP TABLE IF EXISTS `beer`;
-- DROP TABLE IF EXISTS `beerTypeHistory`;
-- DROP TABLE IF EXISTS `manufacturer`;
-- DROP TABLE IF EXISTS `packaging`;
-- DROP TABLE IF EXISTS `beerType`;
--
--
-- CREATE TABLE beerType (
--  -- `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `NAME` VARCHAR(20) NOT NULL,
--   `BEER_TYPE_ID` INT(10) NOT NULL AUTO_INCREMENT,
--   PRIMARY KEY (`BEER_TYPE_ID`) USING BTREE
-- ) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;
--
--
--
-- CREATE TABLE beerTypeHistory (
--  `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `BEER_TYPE_ID` INT(10) NOT NULL,
--   `HISTORY` VARCHAR(1000) NOT NULL,
--   PRIMARY KEY (`ID`) USING BTREE,
--   FOREIGN KEY (BEER_TYPE_ID) REFERENCES beerType(BEER_TYPE_ID)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--
--
--    CREATE TABLE packaging (
--  -- `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `PACKAGING_TYPES` VARCHAR(100) NOT NULL,
--   `PACKAGING_TYPE_ID` INT(10) NOT NULL AUTO_INCREMENT,
--   PRIMARY KEY (`PACKAGING_TYPE_ID`) USING BTREE
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
--
--
--
-- CREATE TABLE beerTypeDescription (
--  -- `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `BEER_TYPE_ID` INT(30) NOT NULL AUTO_INCREMENT,
--   `DESCRIPTION` VARCHAR(1000) NOT NULL,
--   PRIMARY KEY (`BEER_TYPE_ID`) USING BTREE,
--   FOREIGN KEY (BEER_TYPE_ID) REFERENCES beerType(BEER_TYPE_ID)
-- ) ENGINE=InnoDB AUTO_INCREMENT=100 DEFAULT CHARSET=utf8;
--
--
-- CREATE TABLE manufacturer (
--  -- `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `NAME` VARCHAR(30) NOT NULL,
--   `MANUFACTURER_ID` INT(10) NOT NULL AUTO_INCREMENT,
--   PRIMARY KEY (`MANUFACTURER_ID`) USING BTREE
-- ) ENGINE=InnoDB AUTO_INCREMENT=50 DEFAULT CHARSET=utf8;
--
--
-- CREATE TABLE beer (
--   `ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
--   `NAME` VARCHAR(20) NOT NULL,
--   `DESCRIPTION` VARCHAR(200) NOT NULL,
--   `COUNTRY` VARCHAR(20) NOT NULL,
--    `ALC` FLOAT NOT NULL,
--   `BEER_TYPE_ID` INT(10) NOT NULL,
--   `MANUFACTURER_ID` INT(10) NOT NULL,
--   `PACKAGING_TYPE_ID` INT(10) NOT NULL,
--   PRIMARY KEY (`ID`) USING BTREE,
--   FOREIGN KEY (BEER_TYPE_ID) REFERENCES beerType(BEER_TYPE_ID),
--   FOREIGN KEY (MANUFACTURER_ID) REFERENCES manufacturer(MANUFACTURER_ID),
--   FOREIGN KEY (PACKAGING_TYPE_ID) REFERENCES packaging(PACKAGING_TYPE_ID)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `shop`;
DROP TABLE IF EXISTS `type_of_item`;
DROP TABLE IF EXISTS `item_location`;
DROP TABLE IF EXISTS `stuff`;
DROP TABLE IF EXISTS `item`;

CREATE TABLE shop (
  `ID` INT(10) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(20) NOT NULL,
  `SHOP_LOCATION` VARCHAR(50) NOT NULL,
  `ROOM_AREA` INT(10) NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



--
--
-- shop
-- id
-- shop_location
-- room_aria
--
-- item_location
-- item*
-- shop*
--
-- type_of_item
-- id
-- name
--
-- stuff
-- name
-- surname
-- shop*
-- salary
--
-- item
-- id
-- name
-- price
-- type_of_item*
